openapi: 3.0.0
info:
  title: client
  version: '1.0'
servers:
  - url: 'http://nfcstage.appskeeper.com/api'
paths:
  '/apiversion/{platform}':
    get:
      summary: apiversion
      tags: []
      responses:
        '200':
          description: OK
        '':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  msg:
                    type: string
                  result:
                    type: object
                    properties:
                      version_name:
                        type: string
                      platform:
                        type: string
                      update_type:
                        type: string
              examples:
                example:
                  value:
                    code: 200
                    msg: Success
                    result:
                      version_name: '1.1'
                      platform: '1'
                      update_type: '1'
            application/xml:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-api-version
      description: API to get the current version of the application
    parameters:
      - schema:
          type: string
        name: platform
        in: path
        required: true
  /normal:
    post:
      summary: ''
      operationId: post-normal
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_type:
                  type: string
                password:
                  type: string
                full_name:
                  type: string
                shoes_size:
                  type: string
                device_id:
                  type: string
                user_type:
                  type: string
                device_token:
                  type: string
                device_type:
                  type: string
                email:
                  type: string
                image:
                  type: string
            examples: {}
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
        - schema:
            type: string
          in: header
          name: content-type
          description: ''
    parameters: []
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  result:
                    type: object
                    properties:
                      access_token:
                        type: string
                      login_type:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_type:
                  type: string
                device_type:
                  type: string
                device_id:
                  type: string
                email:
                  type: string
                password:
                  type: string
                device_token:
                  type: string
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: basic
