openapi: 3.0.0
info:
  title: client
  version: '1.0'
servers:
  - url: 'http://nfcstage.appskeeper.com/api'
paths:
  '/apiversion/{platform}':
    get:
      summary: Current app version
      tags: []
      responses:
        '200':
          description: OK
        '':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  result:
                    type: object
                    properties:
                      version_name:
                        type: string
                      platform:
                        type: string
                      update_type:
                        type: string
              examples:
                example:
                  value:
                    code: 200
                    msg: Success
                    result:
                      version_name: '1.1'
                      platform: '1'
                      update_type: '1'
            application/xml:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-api-version
      description: API to get the current version of the application
    parameters:
      - schema:
          type: string
        name: platform
        in: path
        required: true
  /normal:
    post:
      summary: Sign Up for client
      operationId: post-normal
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_type:
                  type: string
                password:
                  type: string
                full_name:
                  type: string
                shoes_size:
                  type: string
                device_id:
                  type: string
                user_type:
                  type: string
                device_token:
                  type: string
                device_type:
                  type: string
                email:
                  type: string
                image:
                  type: string
              required:
                - login_type
                - password
                - full_name
                - shoes_size
                - device_id
                - user_type
                - device_token
                - email
            examples: {}
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
        - schema:
            type: string
          in: header
          name: content-type
          description: ''
    parameters: []
  /login:
    post:
      summary: Sign In
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  result:
                    type: object
                    properties:
                      access_token:
                        type: string
                      login_type:
                        type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login_type:
                  type: string
                device_type:
                  type: string
                device_id:
                  type: string
                email:
                  type: string
                password:
                  type: string
                device_token:
                  type: string
              required:
                - login_type
                - device_type
                - email
                - password
                - device_token
      description: Api for authorization
  /plateformlist:
    get:
      summary: Get sales platform list
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  result:
                    type: object
                    properties:
                      selling_platefrom_id:
                        type: integer
                      selling_plateform_title:
                        type: string
      operationId: get-plateformlist
      description: Api for merchant account
  /merchant:
    post:
      summary: Create merchant account
      operationId: post-merchant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  result:
                    type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                login_type:
                  type: string
                user_type:
                  type: string
                device_type:
                  type: string
                user_lat:
                  type: string
                user_long:
                  type: string
                address:
                  type: string
                website:
                  type: string
                selling_plateform:
                  type: string
                sales_per_month:
                  type: string
                year_since_first_sale:
                  type: string
                store_name:
                  type: string
                device_token:
                  type: string
                device_id:
                  type: string
                image:
                  type: string
              required:
                - full_name
                - email
                - phone
                - login_type
                - user_type
                - device_type
                - address
                - year_since_first_sale
                - store_name
                - device_token
                - device_id
      description: ''
  /forgot:
    post:
      summary: Forgot password
      operationId: post-forgot
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      description: API for authorization changes
components:
  schemas:
    SellingPlatform:
      title: SellingPlatform
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        username:
          type: string
        isSelected:
          type: boolean
      required:
        - username
  securitySchemes:
    Authorization:
      type: http
      scheme: basic
