openapi: 3.0.0
info:
  title: client
  version: '1.0'
servers:
  - url: 'http://localhost:3000/api'
paths:
  '/apiversion/{platform}':
    get:
      summary: apiversion
      tags: []
      responses:
        '200':
          description: OK
        '':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  msg:
                    type: string
                  result:
                    type: object
                    properties:
                      version_name:
                        type: string
                      platform:
                        type: string
                      update_type:
                        type: string
              examples:
                example:
                  value:
                    code: 200
                    msg: Success
                    result:
                      version_name: '1.1'
                      platform: '1'
                      update_type: '1'
            application/xml:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get-api-version
      description: API to get the current version of the application
    parameters:
      - schema:
          type: string
        name: platform
        in: path
        required: true
components:
  schemas: {}
